---
abstract: 'Convert hash to xml and xml to hash using LibXML'
author:
  - 'Mons Anderson, C<< <mons at cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Hash-LX
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  XML::Hash::LX:
    file: lib/XML/Hash/LX.pm
    version: 0.0602
requires:
  XML::LibXML: 0
  perl: 5.6.2
resources:
  license: http://dev.perl.org/licenses/
version: 0.0602
